# This makefile aims at procesing all file
# First, TestDict is dictionary that should be generated by root cling.
# Then, all .o file must be generated in order to reduce compile time
# .so library is final aim if no specific excutable file is needed.

# SOURCE = BoardBuffer.cpp BoardsManager.cpp CombineData.cpp Configure.cpp DetectorManager.cpp Loop.cpp TPrimaryData.cpp TCombinedData.cpp FileManager.cpp TDetectorInfo.cpp mppc.cpp
OBJ = FitSpectrum.o	Multi_Gauss.o
HEADER = FitSpectrum.h	Multi_Gauss.h

SHARELIB = libFitSpe.so
SHARE = FitSpe

DICTCXX = TestDict.cxx
LINKDEF = LinkDef.h

Excutable = test


$(SHARELIB): $(OBJ) TestDict.cxx
	`root-config --cxx`	-fPIC	-shared	-o	$@	$(OBJ)	`root-config --cflags --libs` -lSpectrum

%.o: %.cpp %.h
	`root-config --cxx `	-o	$@	-c	$<	`root-config --cflags`	-fPIC

TestDict.cxx: $(HEADER)   LinkDef.h
	rootcling	-f	$@	-c	$(HEADER)	LinkDef.h



clean:
	rm *.o
distclean:
	rm *.so *.pcm *.o *.root *.pdf $(Excutable) *Dict*


test:  test.cpp $(SHARELIB)
	`root-config --cxx `	-o	$@	$<	-L.	-l$(SHARE)	`root-config --cflags --libs`

all: $(Excutable)
