# This makefile aims at procesing all file
# First, TestDict is dictionary that should be generated by root cling.
# Then, all .o file must be generated in order to reduce compile time
# .so library is final aim if no specific excutable file is needed.

# SOURCE = BoardBuffer.cpp BoardsManager.cpp CombineData.cpp Configure.cpp DetectorManager.cpp Loop.cpp TPrimaryData.cpp TCombinedData.cpp FileManager.cpp TDetectorInfo.cpp mppc.cpp
OBJ = 
HEADER = 


# DICTCXX = TestDict.cxx
# LINKDEF = LinkDef.h

Excutable = 


libFitSpe.so: $(OBJ) #TestDict.cxx
	`root-config --cxx --cflags`	-fPIC	-shared	-o	$@	$(OBJ)	TestDict.cxx	`root-config --libs`

%.o: %.cpp %.h
	`root-config --cxx `	-o	$@	-c	$<	`root-config --cflags`	-fPIC

TestDict.cxx: $(HEADER)   LinkDef.h
	rootcling	-f	$@	-c	$(HEADER)	LinkDef.h



clean:
	rm *.o
distclean:
	rm *.so *.pcm *.o *.root *.pdf $(Excutable) *Dict*


test:  test.cpp libFitSpe.so
	`root-config --cxx `	-o	$@	$<	-L.	-lTest	`root-config --cflags --libs`

all: $(Excutable)
