/*
    This is a function that can read from Histo file, which contains spectrum of all channels.
    The file can be generated by 'read.cpp', which read all events from .root file, and save a histrogram to a histo.root file.

*/



#include "TH1.h"
#include "TH1F.h"
#include "TFile.h"

#include <cstdio>
#include <iostream>
#include <fstream>
#include <string>

using namespace std;



TH1F* Read_Spectrum(TFile * File, int Channel)
{
    TH1F * temp = NULL;
    if(File)
    {
        string s = "Chch_";
        s += to_string(Channel);
        s += ";1";
        temp = (TH1F *)File -> Get(s . c_str());
    }
    else
    {
        cout << "Error, file pointer is NULL" << endl;
        return NULL;
    }
    if(!temp)
    {
        cout << "Error, cannot get channel " << Channel << ", please check input channel number or ROOT file." << endl;
    }
    return temp;
}

TH1F * Read_Spectrum(string File_Name, int Channel)
{
    auto file = new TFile(File_Name . c_str());
    auto temp = Read_Spectrum(file, Channel);
    return temp;
}